[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
api = { workspace = true }
urlencoding = "2.1.3"
gloo-timers = { version = "0.3.0", features = ["futures"] }

[features]
server = ["api/server"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.77", features = ["Window", "Storage"] }

[target.wasm32-unknown-unknown.dependencies]
gloo-timers = "0.3.0"
